baseURL = "https://qbart.dev/"
languageCode = "en-gb"
defaultContentLanguage = "en"
title = "tail -f qbart.dev.log"
theme = "hermit"
enableEmoji = true
disqusShortname = "qbart"
GoogleAnalytics = "UA-143750284-1"
footnotereturnlinkcontents = "↩"
pygmentsCodeFences = true
pygmentsStyle="dracula"
copyright="Bartłomiej Wójtowicz"
rssLimit=20

[author]
name = "Bartłomiej Wójtowicz"

[taxonomies]
tag = "tags"

[Params]
customCSS = ["css/custom.css"]
dateform        = "Jan 2, 2006"
dateformShort   = "Jan 2"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
code_copy_button = true
homeSubtitle = "Bartłomiej Wójtowicz - a software engineer"

[[Params.Social]]
name = "email"
url = "mailto:qbartATpm.me"

[[Params.Social]]
name = "github"
url = "https://github.com/qbart"

[[Params.Social]]
name = "linkedin"
url = "https://www.linkedin.com/in/bartlomiej-wojtowicz-24b58b1b"

[[Params.Social]]
name = "twitter"
url = "https://twitter.com/softkiwi"

[[Params.Social]]
name = "pinterest"
url = "https://pinterest.com/bartlomiejwojtowicz/"


[permalinks]
posts = "/:section/:year/:slug"

[[menu.main]]
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
name = "Open source"
url = "/projects/"
weight = 30

[[menu.main]]
name = "Bookmarks"
url = "https://b.qbart.dev"
weight = 40

